FROM php:7.4-apache

#ENV Variables
ENV APP_DIR=/var/www/html/
ENV APP_PORT=80

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install python3 -y
RUN apt install -y python3-pip
RUN apt install -y build-essential libssl-dev libffi-dev python3-dev
RUN apt install ffmpeg nano -y

#App dir
WORKDIR ${APP_DIR}
#Copy Dependencies
COPY . ${APP_DIR}
RUN pip3 install -r requirements.txt

#Expose Port
EXPOSE ${APP_PORT}
